[package]
name = "anders-gameboy-emulator"
version = "0.1.0"
authors = ["Anders Conbere <anders@conbere.org>"]

[dependencies.sdl2]
  version = "0.31"
  default-features = false
  features = ["ttf"]
[dependencies.clap]
  version = "2.32.0"
